fixing depth

diff --git a/.github/workflows/_build.yml b/.github/workflows/_build.yml
--- a/.github/workflows/_build.yml
+++ b/.github/workflows/_build.yml
@@ -18,11 +18,87 @@ defaults:
 
 jobs:
   Setup:
-    name: Project Setup
+    name: Install Dependencies
+    runs-on: macos-11
     permissions:
       statuses: write
       pull-requests: write
-    uses: ./.github/workflows/_project-setup.yml
+    steps:
+      - name: Set build image var
+        run: echo "ImageVersion=$ImageVersion"  >> $GITHUB_ENV
+
+      # Checkout the repo
+      - uses: actions/checkout@v3
+
+      # If a different version of bundler has been used, CI will fail with a very unhelpful error message at `bundle install`.
+      # This is hopefully somewhat more helpful:
+      - name: Verify Bundler Version
+        run: if [[ $(cat Gemfile.lock | sed -n '/BUNDLED WITH/{n;p;}' | sed '/^$/d;s/[[:blank:]]//g') != "2.2.3" ]]; then echo "Error - Gemfile.lock should be bundled with bundler 2.2.3"; exit 64; fi
+
+      - name: Set GIT_TAG
+        id: extract_git_tag
+        run: |
+          if [[ $GITHUB_REF == "refs/tags/"* ]]
+          then
+            echo ::set-output name=GIT_TAG::${GITHUB_REF#refs/tags/}
+          else
+            echo ::set-output name=GIT_TAG::""
+          fi
+
+      - name: Print tag
+        run: echo ${{ steps.extract_git_tag.outputs.GIT_TAG }}
+
+      - name: Select Xcode 13
+        run: sudo xcode-select --switch /Applications/Xcode_13.2.1.app
+
+      - name: Install clang format
+        run: brew install clang-format@14
+
+      - name: Install sourcekitten
+        run: brew install sourcekitten
+
+      - name: nvm install
+        run: nvm install
+
+      - name: Set Ruby version
+        uses: ruby/setup-ruby@v1 # Sets ruby version via `.ruby-version`
+
+      - name: Set Bundler Config
+        run: bundle config path vendor/bundle
+
+      - name: Cache Bundler install Gems
+        uses: actions/cache@v3
+        with:
+          path: vendor/bundle
+          key: ${{ runner.os }}-gems-${{ env.ImageVersion }}-${{ hashFiles('**/Gemfile.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-gems-${{ env.ImageVersion }}
+
+      - name: Cache Pods
+        uses: actions/cache@v3
+        with:
+          path: Example/Pods
+          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-pods-
+
+      - name: NPM ci
+        run: |
+          nvm use
+          npm ci
+
+      - name: Bundle Install
+        run: bundle install --jobs 4 --retry 3
+
+      - name: "Erase content from simulators"
+        run: "pkill Simulator || xcrun simctl erase all"
+
+      - name: Pod Install
+        run: bundle exec pod install
+        working-directory: Example
+
+      - name: Run NPM build
+        run: npm run build
 
   Lint:
     name: Lint Project
@@ -40,13 +116,6 @@ jobs:
         run: npm run danger
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  BuildDocs:
-    name: Project Setup
-    permissions:
-      statuses: write
-      pull-requests: write
-    uses: ./.github/workflows/_build-docs.yml
 
   BuildUIKit:
     name: Build UIKit
